events {}

http {

    upstream web_frontend {
        server web-frontend-server:80;
    }

    upstream app_backend {
        server application-backend-server:8081;
    }

    upstream auth_service {
        server authentication-identity-server:8080;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://web_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://app_backend/;
            proxy_set_header Host $host;
        }

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
        }
    }
}